import React, { useRef } from 'react';
import { X, Printer, Download, ShieldCheck, ShieldAlert, Award, Calendar, Laptop } from 'lucide-react';
import { ScanEvaluation, Scenario, Finding } from '../types';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  evaluation: ScanEvaluation;
  scenario: Scenario;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  evaluation,
  scenario
}) => {
  const reportRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadHtml = () => {
    if (!reportRef.current) return;
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>System Trust Scanner - Report</title>
  <style>
    body { font-family: sans-serif; background: #0b0f19; color: #e2e8f0; padding: 24px; }
    .card { background: #131b2e; border: 1px solid #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 16px; }
    .tier-Critical { color: #f43f5e; font-weight: bold; }
    .tier-High { color: #f97316; font-weight: bold; }
    .tier-Medium { color: #f59e0b; font-weight: bold; }
    .tier-Low { color: #10b981; font-weight: bold; }
  </style>
</head>
<body>
  ${reportRef.current.innerHTML}
</body>
</html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `system_trust_report_${Date.now()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        
        {/* Header */}
        <div className="bg-slate-950 px-6 py-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-cyan-500/20 text-cyan-400">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-100">
                System Security & Trust Audit Report
              </h3>
              <p className="text-xs text-slate-400">
                Generated by System Trust Scanner • NUST CyberHub
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={handleDownloadHtml}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-cyan-600 hover:bg-cyan-500 text-white transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download HTML</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-100 hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-6 sm:p-8 flex-1 overflow-y-auto bg-slate-950/60" ref={reportRef}>
          
          {/* Header Banner */}
          <div className="border-b border-slate-800 pb-6 mb-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div className="text-xs font-bold uppercase tracking-wider text-cyan-400 mb-1">
                  NUST CyberHub — Cybersecurity Innovation Challenge
                </div>
                <h1 className="text-2xl font-black text-slate-100 tracking-tight">
                  System Trust & Remote Access Audit
                </h1>
                <p className="text-xs text-slate-400 mt-1">
                  Target Profile: <strong>{scenario.name}</strong> • Reference ID: STS-{Math.floor(Math.random() * 89999 + 10000)}
                </p>
              </div>

              <div className="bg-slate-900 border border-slate-800 p-3 rounded-xl text-right">
                <div className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">Audit Status</div>
                <div className={`text-lg font-black ${
                  evaluation.tier === 'Critical' ? 'text-rose-400' :
                  evaluation.tier === 'High' ? 'text-orange-400' :
                  evaluation.tier === 'Medium' ? 'text-amber-400' : 'text-emerald-400'
                }`}>
                  {evaluation.tier.toUpperCase()} RISK ({evaluation.finalRiskScore}/100 pts)
                </div>
                <div className="text-[11px] text-slate-300 font-mono">
                  Trust Score: {evaluation.trustScore}%
                </div>
              </div>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="bg-slate-900/80 border border-slate-800 p-5 rounded-2xl mb-6">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">
              Executive Summary
            </h3>
            <p className="text-sm text-slate-200 leading-relaxed mb-3">
              {evaluation.summaryMessage}
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs pt-3 border-t border-slate-800">
              <div>
                <span className="text-slate-400">Network Sockets Flagged:</span>
                <span className="block font-bold text-slate-100">{evaluation.moduleFindingsCount.network}</span>
              </div>
              <div>
                <span className="text-slate-400">Process Path Alerts:</span>
                <span className="block font-bold text-slate-100">{evaluation.moduleFindingsCount.integrity}</span>
              </div>
              <div>
                <span className="text-slate-400">Startup Persistence:</span>
                <span className="block font-bold text-slate-100">{evaluation.moduleFindingsCount.persistence}</span>
              </div>
              <div>
                <span className="text-slate-400">Active RAT Programs:</span>
                <span className="block font-bold text-slate-100">{evaluation.moduleFindingsCount.rats}</span>
              </div>
            </div>
          </div>

          {/* Correlated Threat Multiplier Notice */}
          {evaluation.correlationBoost > 0 && (
            <div className="bg-rose-950/40 border border-rose-800 p-4 rounded-xl mb-6">
              <h4 className="text-xs font-bold uppercase text-rose-300 tracking-wider mb-1">
                Correlated Threat Multiplier Applied (+{evaluation.correlationBoost} Risk Points)
              </h4>
              <p className="text-xs text-slate-300">
                Multiple correlated indicators were identified converging on the same process. As specified in the challenge scoring architecture, combined anomalies (untrusted execution path + live outbound socket + startup auto-run) trigger elevated risk scoring to reflect active compromise.
              </p>
            </div>
          )}

          {/* Detailed Findings List */}
          <div className="space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Detailed Findings & Plain-Language Remediation ({evaluation.findings.length})
            </h3>

            {evaluation.findings.length === 0 ? (
              <p className="text-xs text-emerald-400 bg-emerald-950/30 p-4 rounded-xl border border-emerald-900">
                No active threats detected. System exhibits standard OS baseline behavior.
              </p>
            ) : (
              evaluation.findings.map((f: Finding, i: number) => (
                <div key={f.id} className="bg-slate-900 border border-slate-800 rounded-xl p-4 text-xs space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-100">
                      {i + 1}. [{f.moduleId.toUpperCase()}] {f.title}
                    </span>
                    <span className="font-mono text-rose-400 font-bold">
                      +{f.riskPoints} pts
                    </span>
                  </div>
                  <div className="text-slate-300 font-mono text-[11px] bg-slate-950 p-2 rounded">
                    {f.technicalDetails}
                  </div>
                  <div className="text-slate-200">
                    <strong>Plain-Language Meaning: </strong>{f.plainLanguageExplanation}
                  </div>
                  <div className="text-amber-300/90">
                    <strong>Mobile Money Vulnerability: </strong>{f.mobileMoneyImpact}
                  </div>
                  <div className="text-emerald-400/90 font-semibold">
                    <strong>Action Required: </strong>{f.recommendedAction}
                  </div>
                </div>
              ))
            )}
          </div>

        </div>

      </div>
    </div>
  );
};
